### ISSUE TITLE
Use @is_cached to Prevent nil and false From Reexecuting the Block

### ISSUE THREAD

**Issue by sshaw** [simple-updates/simple-lazy#1]
If the block returns `false` or `nil`, `unless @cached` will not be skipped: https://github.com/simple-updates/simple-lazy/blob/de8da8fcbe32ec71af4a281812d6b0bbcaa81252/lib/simple/lazy.rb#L31

**Comment by sshaw** [comment]
PS don't forget about overloading `#respond_to?` otherwise `user.respond_to?(:tweets)` etc... won't work.

**Comment by localhostdotdev** [comment]
oops thanks, both were mistakes
