### ISSUE TITLE
Need a clearer documentation

### ISSUE THREAD

**Issue by PikachuEXE** [simple-updates/simple-lazy#2]
I am really not sure when the input value is used and when the block is called

`#hash` => `value`
`#cached` => block value
`#cached?` => whether block result is cached
`#to_s` =>`cached.to_s` (dunno why need `to_s` but anyway)
`#methods` => `methods + cached.methods` (won't cause infinite recursive call?)
Other methods like `#xxx` => `cached.xxx`

**Comment by localhostdotdev** [comment]
i'm not sure what changes you are suggesting, if people need to know exactly when the value is fetched then they can read the source code and the tests. the idea is that you mostly don't need to care about when it is fetched or not.
